//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 02:31:21 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.soap.bjsbt_01.bitguiders.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bitguiders.bjsbt_01.soap.service;
